# [START gae_quickstart_yaml]
runtime: nodejs10

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0
  min_idle_instances: automatic
  max_idle_instances: 0
# [END gae_quickstart_yaml]